language: R
cache: packages
warnings_are_errors: true

env:
  global:
    - secure: "D3YmGw0IpIxJiY4gi+e3VaFGTdYedEuTmB29dnMmBt1jrtwWrtBI2YE7bA0CZf/Hzbv3Zyk/WXKgsgQAcrZgkVaEi/cf0Rz61uWLV9n9G7hx3FT53cxAysZiaE3r5zIaXNln6QC92e66v86nOYv19uRfzZHOvly5UPHOPcGefKx8lyBXIF8BBPLJmbxm0B36NjXzg7dTKWYLwYScN+R2eDqUkp3gVcRKlKJRFFDbWu0QG1uxlTAMnbKhMCIFYmW/LAK1pvU7mlTNHI35AJz54eYZcaZ+NNN2FzmoGamSDHPasc/M7Av7MLj6ThFIkgTc5OX+3lJ+R4CuRPlqsiKiab8lI6sLT82F0S4wkwnOtxSMpciHiVSZlBk2WKHToOj2hUf6IC/SOApMNhuRHPtKluoqF4kL5w6xyL2f2TWfl7vq0trnJAN2LSsv5vmriTOV7XGQ+EMUbyts3xSlCJbI/EVJQpFycyzCfUFnAlsH61wjxUXX0b0RfN4X9N2X2qOQVRSiUNVbXC/XiYyCIWOOCUcRx1r/KcAgJN1kKseZy4Dlqy0I8ZwjwoMY50Vp8CFTomdNVo4PcJYlKS9gEtAw05zjSDS1jKCmnjZAuTJYPOdeTYnZjOznIqp2ADw16D5/ROdCvPq9ogf3fQN/3IR6skUHx4JBD4ngS53HbImVe/U="
