language: R
cache: packages
warnings_are_errors: true

env:
  global:
    - secure: "C6k/yi2qpZ/75YJYHMQQ80ygC9EYaU0i4wJXoZaunNS+rRKaFulCOQrkmioWJ4eiSmNCO3BwN1KYoIFtEFMe72VvVgv5KPvSUl47HN5OhOITs7xw3eq2KSwiOsUo+C3NmcWzqn6Qtc7CDe1whGRA7XzkQ+J8HG8mFcbmookF/JxvSVpiJdrfzrEXbnCbHuyppAixA65eekW5QPFw135WwRjsAPjDQkZY3D7e6aM0ly0HpfGYyvnPCPlm3yqYSXo81qsaK0bGXJ6P7r438i1WaBHIdhDCYNYwcRL5iUVhm1siS45u/HYEgzrCo6mbWNsd+nJu8JcCjmhtDi4OghDidl65qRFrPS54WlQbW1iwwyKj3SL2Tlf+l9qiCEgp1/RMVACU+R7HQl+VBG+7vX8ScGDRNrImNwbv2Xy9MtPRXlnvW02luoB5j7tTa/zJv0Slryf8pWUkykgx6Hj205WOFIFPrR7u7zNMOQxKtdwfflKWG7cluM73hSm2gATh5AkTRiCH565EHqNU1YmJhWeJanNwapgQYBQBQebZlRm6je0q+CazyTs2hC0wVa28csaoSJF0bfVnmgvq2NhJmvOPnv6Mq8KX/W90VNkj6EIGisIMEE57sAFUlZbF1hNkdUp2uedPjIVySv97VcXSWmIajAVQCwbyU6OdanSXimYkwis="
